# Build migration WITHOUT BOM - includes learning_paths + stages + courses
$ErrorActionPreference = 'Stop'

$v2Path = Join-Path $PSScriptRoot '..\career_stage_courses_direct_links_v2.sql'
$v2Lines = [System.IO.File]::ReadAllLines((Resolve-Path $v2Path).Path, [System.Text.Encoding]::UTF8)

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("-- Migration: Load career_stage_courses_direct_links_v2 data")
[void]$sb.AppendLine("-- Adds new columns, creates missing learning paths/stages, and loads v2 courses.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- 1. Add new columns to courses table (idempotent)")
[void]$sb.AppendLine("ALTER TABLE courses ADD COLUMN IF NOT EXISTS provider TEXT;")
[void]$sb.AppendLine("ALTER TABLE courses ADD COLUMN IF NOT EXISTS page_type TEXT;")
[void]$sb.AppendLine("ALTER TABLE courses ADD COLUMN IF NOT EXISTS level TEXT;")
[void]$sb.AppendLine("ALTER TABLE courses ADD COLUMN IF NOT EXISTS direct_link_note TEXT;")
[void]$sb.AppendLine("ALTER TABLE courses ADD COLUMN IF NOT EXISTS relevance_reason TEXT;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- 2. Drop old course data (the v1 generated search URLs)")
[void]$sb.AppendLine("DELETE FROM courses;")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- 3. Create temp table matching v2 SQL structure")
[void]$sb.AppendLine("DROP TABLE IF EXISTS tmp_v2_courses;")
[void]$sb.AppendLine("CREATE TEMP TABLE tmp_v2_courses (")
[void]$sb.AppendLine("    career_identifier TEXT NOT NULL,")
[void]$sb.AppendLine("    career_name TEXT NOT NULL,")
[void]$sb.AppendLine("    stage_no TEXT NOT NULL,")
[void]$sb.AppendLine("    stage_id TEXT NOT NULL,")
[void]$sb.AppendLine("    stage_name TEXT NOT NULL,")
[void]$sb.AppendLine("    sort_order TEXT NOT NULL,")
[void]$sb.AppendLine("    course_identifier TEXT NOT NULL,")
[void]$sb.AppendLine("    course_title TEXT NOT NULL,")
[void]$sb.AppendLine("    subtitle_th TEXT,")
[void]$sb.AppendLine("    provider TEXT,")
[void]$sb.AppendLine("    source_code TEXT,")
[void]$sb.AppendLine("    source_name TEXT,")
[void]$sb.AppendLine("    cost_model TEXT,")
[void]$sb.AppendLine("    page_type TEXT,")
[void]$sb.AppendLine("    level TEXT,")
[void]$sb.AppendLine("    direct_course_url TEXT,")
[void]$sb.AppendLine("    direct_link_note TEXT,")
[void]$sb.AppendLine("    relevance_reason TEXT")
[void]$sb.AppendLine(");")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- 4. Load v2 data into temp table")

# Insert line from v2 file
$insertLine = $v2Lines[4] -replace 'INSERT INTO career_stage_courses', 'INSERT INTO tmp_v2_courses'
$insertLine = $insertLine.TrimStart([char]0xFEFF)
[void]$sb.AppendLine($insertLine)

for ($i = 5; $i -lt $v2Lines.Count; $i++) {
    $line = $v2Lines[$i]
    if ($line.Trim().Length -gt 0) {
        [void]$sb.AppendLine($line)
    }
}

# 5. Create learning_paths from temp table
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- 5. Create learning_paths for all careers in v2 data")
[void]$sb.AppendLine("INSERT INTO learning_paths (id, career_identifier, career_name, description, total_stages)")
[void]$sb.AppendLine("SELECT")
[void]$sb.AppendLine("    gen_random_uuid(),")
[void]$sb.AppendLine("    career_identifier,")
[void]$sb.AppendLine("    career_name,")
[void]$sb.AppendLine("    'Learning path with 6 stages for ' || career_name,")
[void]$sb.AppendLine("    MAX(CAST(stage_no AS INTEGER))")
[void]$sb.AppendLine("FROM tmp_v2_courses")
[void]$sb.AppendLine("GROUP BY career_identifier, career_name")
[void]$sb.AppendLine("ON CONFLICT (career_identifier) DO UPDATE SET")
[void]$sb.AppendLine("    career_name = EXCLUDED.career_name,")
[void]$sb.AppendLine("    description = EXCLUDED.description,")
[void]$sb.AppendLine("    total_stages = EXCLUDED.total_stages,")
[void]$sb.AppendLine("    updated_at = NOW();")

# 6. Create stages
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- 6. Create stages for all careers in v2 data")
[void]$sb.AppendLine("WITH seed_stages AS (")
[void]$sb.AppendLine("    SELECT DISTINCT")
[void]$sb.AppendLine("        career_identifier,")
[void]$sb.AppendLine("        career_name,")
[void]$sb.AppendLine("        CAST(stage_no AS INTEGER) AS stage_number,")
[void]$sb.AppendLine("        career_identifier || '_stage_' || stage_no AS stage_identifier,")
[void]$sb.AppendLine("        stage_name")
[void]$sb.AppendLine("    FROM tmp_v2_courses")
[void]$sb.AppendLine(")")
[void]$sb.AppendLine("INSERT INTO stages (")
[void]$sb.AppendLine("    id, learning_path_id, stage_number, stage_identifier, title, subtitle,")
[void]$sb.AppendLine("    position_top, position_left, position_right, position_bottom, position_transform")
[void]$sb.AppendLine(")")
[void]$sb.AppendLine("SELECT")
[void]$sb.AppendLine("    gen_random_uuid(),")
[void]$sb.AppendLine("    lp.id,")
[void]$sb.AppendLine("    ss.stage_number,")
[void]$sb.AppendLine("    ss.stage_identifier,")
[void]$sb.AppendLine("    ss.stage_name,")
[void]$sb.AppendLine("    CASE ss.stage_number")
[void]$sb.AppendLine("        WHEN 1 THEN 'Start with core foundations'")
[void]$sb.AppendLine("        WHEN 2 THEN 'Build core knowledge'")
[void]$sb.AppendLine("        WHEN 3 THEN 'Practice essential job skills'")
[void]$sb.AppendLine("        WHEN 4 THEN 'Deepen specialized skills'")
[void]$sb.AppendLine("        WHEN 5 THEN 'Create portfolio work'")
[void]$sb.AppendLine("        WHEN 6 THEN 'Prepare for career launch'")
[void]$sb.AppendLine("        ELSE ss.stage_name")
[void]$sb.AppendLine("    END,")
[void]$sb.AppendLine("    CASE ss.stage_number WHEN 1 THEN '1%' WHEN 2 THEN '17%' WHEN 3 THEN '26%' WHEN 4 THEN '38%' ELSE NULL END,")
[void]$sb.AppendLine("    CASE ss.stage_number WHEN 1 THEN '62%' WHEN 4 THEN '23%' WHEN 6 THEN '25%' ELSE NULL END,")
[void]$sb.AppendLine("    CASE ss.stage_number WHEN 2 THEN '55%' WHEN 3 THEN '15%' WHEN 5 THEN '23%' ELSE NULL END,")
[void]$sb.AppendLine("    CASE ss.stage_number WHEN 5 THEN '33%' WHEN 6 THEN '3%' ELSE NULL END,")
[void]$sb.AppendLine("    CASE ss.stage_number WHEN 1 THEN 'translateX(-50%)' ELSE NULL END")
[void]$sb.AppendLine("FROM seed_stages ss")
[void]$sb.AppendLine("JOIN learning_paths lp ON lp.career_name = ss.career_name")
[void]$sb.AppendLine("ON CONFLICT (learning_path_id, stage_number) DO UPDATE SET")
[void]$sb.AppendLine("    stage_identifier = EXCLUDED.stage_identifier,")
[void]$sb.AppendLine("    title = EXCLUDED.title,")
[void]$sb.AppendLine("    subtitle = EXCLUDED.subtitle,")
[void]$sb.AppendLine("    position_top = EXCLUDED.position_top,")
[void]$sb.AppendLine("    position_left = EXCLUDED.position_left,")
[void]$sb.AppendLine("    position_right = EXCLUDED.position_right,")
[void]$sb.AppendLine("    position_bottom = EXCLUDED.position_bottom,")
[void]$sb.AppendLine("    position_transform = EXCLUDED.position_transform,")
[void]$sb.AppendLine("    updated_at = NOW();")

# 7. Insert courses
[void]$sb.AppendLine("")
[void]$sb.AppendLine("-- 7. Normalize from temp table into courses")
[void]$sb.AppendLine("INSERT INTO courses (")
[void]$sb.AppendLine("    id, stage_id, course_identifier, title, subtitle,")
[void]$sb.AppendLine("    source_code, source_name, cost_type, url, sort_order,")
[void]$sb.AppendLine("    notes, provider, page_type, level, direct_link_note, relevance_reason")
[void]$sb.AppendLine(")")
[void]$sb.AppendLine("SELECT DISTINCT ON (v.course_identifier)")
[void]$sb.AppendLine("    gen_random_uuid(), s.id, v.course_identifier, v.course_title,")
[void]$sb.AppendLine("    COALESCE(v.subtitle_th, ''), v.source_code, v.source_name,")
[void]$sb.AppendLine("    v.cost_model, v.direct_course_url, CAST(v.sort_order AS INTEGER),")
[void]$sb.AppendLine("    NULL, v.provider, v.page_type, v.level, v.direct_link_note, v.relevance_reason")
[void]$sb.AppendLine("FROM tmp_v2_courses v")
[void]$sb.AppendLine("JOIN learning_paths lp ON lp.career_name = v.career_name")
[void]$sb.AppendLine("JOIN stages s ON s.learning_path_id = lp.id AND s.stage_number = CAST(v.stage_no AS INTEGER)")
[void]$sb.AppendLine("ON CONFLICT (course_identifier) DO UPDATE SET")
[void]$sb.AppendLine("    stage_id = EXCLUDED.stage_id, title = EXCLUDED.title,")
[void]$sb.AppendLine("    subtitle = EXCLUDED.subtitle, source_code = EXCLUDED.source_code,")
[void]$sb.AppendLine("    source_name = EXCLUDED.source_name, cost_type = EXCLUDED.cost_type,")
[void]$sb.AppendLine("    url = EXCLUDED.url, sort_order = EXCLUDED.sort_order,")
[void]$sb.AppendLine("    provider = EXCLUDED.provider, page_type = EXCLUDED.page_type,")
[void]$sb.AppendLine("    level = EXCLUDED.level, direct_link_note = EXCLUDED.direct_link_note,")
[void]$sb.AppendLine("    relevance_reason = EXCLUDED.relevance_reason, updated_at = NOW();")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("DROP TABLE IF EXISTS tmp_v2_courses;")

$outPath = Join-Path $PSScriptRoot 'migrations\000005_update_courses_v2.up.sql'
$encoding = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), $encoding)

$bytes = [System.IO.File]::ReadAllBytes($outPath)
if ($bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
    Write-Output "WARNING: BOM still present!"
} else {
    Write-Output "No BOM - file is clean"
}
Write-Output ("File size: " + (Get-Item $outPath).Length)
